# Copyright 2020 Appvia Ltd <info@appvia.io>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# RedisGraph
---
apiVersion: v1
kind: Service
metadata:
  name: redisgraph
  labels:
    {{- include "krane.labels" . | nindent 4 }}
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    {{- include "krane.redisgraphSelectorLabels" . | nindent 4 }}

# Krane
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "krane.fullname" . }}
  labels:
    {{- include "krane.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "krane.selectorLabels" . | nindent 4 }}
