version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: docile
    versions:
    - 1.3.5
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
    - 1.9.0
    - 1.9.1
  - dependency-name: activesupport
    versions:
    - 6.1.1
    - 6.1.2
    - 6.1.2.1
    - 6.1.3
  - dependency-name: test-unit
    versions:
    - 3.3.9
  - dependency-name: ruby-prof
    versions:
    - 1.4.2
  - dependency-name: redisgraph
    versions:
    - 2.0.1
